//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnikiInternetowe.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int FileId { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> LastUpdateTs { get; set; }
        public string FileSrc { get; set; }
        public bool IsEdited { get; set; }
    }
}
