//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnikiInternetowe.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileContent
    {
        public int FileId { get; set; }
        public bool IsEdited { get; set; }
        public string FileContent1 { get; set; }
        public string Name { get; set; }
    }
}
